[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"
  # Disable problematic features
  GATSBY_CPU_COUNT = "1"
  SKIP_PREFLIGHT_CHECK = "true"